name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "230b9cb7c977160f6a266ae85871ec2946d24ed1e2c30742dc54b590f1d73793"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
