name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3321c8fc3419c9e610f873842dbe3d7242f1e90ba67f6e1f36a991f3b9236aa"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
