name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dda5d636f309956877e936f8ec64f2634d68896c23da493defd8fc49d173a93e"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
