name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff16d1eda80836ea70fa5fed9750b74b10404ffe49df0c93139ea661ce0ee79a"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
