name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5418c8ea82fe3a92eeebef97aa06f3ace128ae49cfd350c08c201ea1a44317d1"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
