name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab4e2b1bb351d507601462cad9456a909651f4b05f5ba4d367df1b51f553480c"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
