name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4f242617843c149925b3ce99da128f23d191ff17c453a942347d8edbcf08fdc"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
