name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3298ced3e25269de8ea2805b23ded6dfcde84e1dadaa8364ad646d0ec573df9"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
