name = "Dartis-Craft AxB Kinpack"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc2bd2e16f617dd76f80633229010b381b8cad155a5daa6aff229943c4738750"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
