name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "215fb27079ff1d7f43bf937e5dcd68c18badc1fdad1ce80ff0b2b032de78283d"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
