name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "628ef60656dabd33bb2a2a04b0691163f3fdaf52678e27488bc69ddfe5b2d8df"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
