name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aff98c39c388adc16216a5a9cf1d0a2ba4916ea10b2c17614f13250ac8e0ebc"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
