name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae1dfd4253b4d28505fa8ab4e1e2e0c676e3fe9977af43bf9ea3e12db10c8718"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
