name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b26b7528f695e9b3560bb03607a709f957e5105bebcd24476458f4d80d6d2239"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
