name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d177cddc2bed4604974b48af967d1261dac19f9d87c2baa6096c6a5dea75060e"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
