name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42865e00793c0794b470c71532bfa98fe20f26eaf708cb480b08df40c68951cc"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
