name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7499e55ee231b3e4c8e1f1c98fe15bc82ea83b95db4d0e458e6797d252e3f768"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
