name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7aaf7c318a904526b6d2c9bbc9131060aea2a578f2c1a03ae6100b0f28f660b0"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
