name = "Dartis-Craft Alex TrainCraft"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c10380d53a0533e9942251bf9aa8e3e648e2737695c4601938251bdb8e76c873"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
